### ISSUE TITLE
FetchError: maximum redirect reached

### ISSUE THREAD

**Issue by chris48s** [awesome-webextension/webextension-store-meta#2]
Hello.

Recently all our calls via this lib are failing with `FetchError: maximum redirect reached`

Example failing code:

```js
import ChromeWebStore from 'webextension-store-meta/lib/chrome-web-store/index.js'

await ChromeWebStore.load({ id: 'iocghaljaochhkgajdilelogdkejkiil' })
```

**Comment by cachho** [comment]
Can confirm

**Comment by crimx** [comment]
Looking into it. Looks like a new Chrome Web Store was launched.

**Comment by crimx** [comment]
webextension-store-meta@1.1.0

**Comment by chris48s** [comment]
This seems to still be happening for some subset of extensions.

```js
import ChromeWebStore from 'webextension-store-meta/lib/chrome-web-store/index.js'

await ChromeWebStore.load({ id: 'iocghaljaochhkgajdilelogdkejkiil' })
```

works just fine

but

```js
import ChromeWebStore from 'webextension-store-meta/lib/chrome-web-store/index.js'

await ChromeWebStore.load({ id: 'hkgmldnainaglpjngpajnnjfhpdjkohh' })
```

still throws `FetchError: maximum redirect reached at` using v1.1.0

**Comment by xmcp** [comment]
I encountered this problem today with my extension that comes with non-ASCII(id=jklfcpboamajpiikgkbjcnnnnooefbhh).

I debugged the problem and figured out that Chrome Web Store is not properly escaping non-ASCII characters in HTTP response headers. Instead they are encoded in UTF-8 [which is not compliant to the standard](https://stackoverflow.com/questions/4400678/what-character-encoding-should-i-use-for-a-http-header):

```
$ curl https://chromewebstore.google.com/detail/jklfcpboamajpiikgkbjcnnnnooefbhh -v
...
< HTTP/2 302
...
< location: https://chromewebstore.google.com/detail/pakku：哔哩哔哩弹幕过滤器/jklfcpboamajpiikgkbjcnnnnooefbhh
...
```

The builtin `http`/`https` package in NodeJS cannot decode this header in UTF-8, leading to wrong redirected URL, as shown in the below screenshot:

![image](https://github.com/awesome-webextension/webextension-store-meta/assets/6646473/2de8eca9-cc54-4184-9b73-231b1ba577e6)

**Comment by xmcp** [comment]
From the above mention, it seems that `nodejs/undici` has just fixed UTF-8 encoding in headers.

I can figure out a PR to use undici for the `fetchText` function, if that is welcomed.

**Comment by xmcp** [comment]
See #3

**Comment by crimx** [comment]
Nice catch! PRs are certainly welcomed. Thanks in advance!
