### ISSUE TITLE
feature request: typescript support

### ISSUE THREAD

**Issue by cachho** [awesome-webextension/webextension-store-meta#4]
I added ES-module support for typescript support. It's outdated, but it worked, but I don't really know what I'm doing, so I didn't feel confident to open a PR, here's the code: https://github.com/cachho/webextension-store-meta

Now, with the breaking changes, I know that from my last attempt that I rather not do it again, so with this issue I'm asking if anyone could at typescript support. Thank you.

**Comment by crimx** [comment]
Hi thanks for the input! I initially wrote this lib for shield.io and thought the API is simple so didn't add the TypeScript overhead. Looks like it is getting more and more adoptions recently. I think this is the right time to rewrite a TypeScript version.

**Comment by crimx** [comment]
Oh I see why you are not getting type hints 😂️. This empty line is the culprit.

https://github.com/awesome-webextension/webextension-store-meta/blob/5088a5a2c21699919ba2a4beaf0525227cbb63e1/lib/chrome-web-store/index.js#L14

**Comment by crimx** [comment]
Looks like I deleted some type comments accidentally.

**Comment by crimx** [comment]
`webextension-store-meta@1.2.0` published. You could give it a try and see if there are any issues.
