### ISSUE TITLE
Downstreams are broken due to changed API behavior

### ISSUE THREAD

**Issue by xmcp** [awesome-webextension/webextension-store-meta#6]
ref: https://github.com/badges/shields/pull/10094

Currently [shields.io](https://github.com/badges/shields/blob/d8e3452fd2ed9d4f04f89c31972f5c3dba257497/services/chrome-web-store/chrome-web-store-base.js#L8) use this library like this:

```javascript
import ChromeWebStore from 'webextension-store-meta/lib/chrome-web-store/index.js'
...
async fetch({ storeId }) {
    return await ChromeWebStore.load({ id: storeId })
    ...
}
```

However, `console.log(ChromeWebStore)` for v1.2.1 now gives us:

```javascript
{
  ChromeWebStore: [class ChromeWebStore],
  default: [class ChromeWebStore]
}
```

Therefore it crashes with `TypeError: ChromeWebStore.load is not a function`.

[badgen](https://github.com/badgen/badgen.net/blob/main/pages/api/chrome-web-store.ts#L2) uses this library in a similar manner, which would also crash (but I haven't tested).

**Comment by xmcp** [comment]
Since the README says `import { ChromeWebStore} ...` instead of `import ChromeWebStore ...`, I'm not sure is it a bug or an intended behavior.

But anyway it is a very serious issue that all downstream libs are totally broken.

**Comment by xmcp** [comment]
Interoperating between ESM and CJS seems challenging: https://github.com/microsoft/TypeScript/issues/2719

However, if we can assume that this library only works for CJS not ESM, we just write `export = foo` in TS and it will be transpiled into `module.exports = foo`.

See https://github.com/microsoft/TypeScript/issues/2719 and https://www.typescriptlang.org/docs/handbook/modules/reference.html#export--and-import--require

**Comment by xmcp** [comment]
So changing from `export default ChromeWebStore;` to `export = ChromeWebStore;` should revert to the old behavior.

(The README also needs to change back to the old API signature of `const ChromeWebStore = ...`.

**Comment by crimx** [comment]
Thanks for the input. I see it's not easy to maintain a TypeScript lib with `export =`. I think I'll keep the `const { ChromeWebStore }` and add a breaking notice to CHANGELOG.
