### ISSUE TITLE
`.version()` returning null

### ISSUE THREAD

**Issue by chris48s** [awesome-webextension/webextension-store-meta#7]
example call:

```js
import { ChromeWebStore } from 'webextension-store-meta/lib/chrome-web-store/index.js'

const data = await ChromeWebStore.load({ id: 'ikhdkkncnoglghljlkmcimlnlhkeamad' })

console.log(data.version())
```

seems to be broken for all examples I've checked.

**Comment by crimx** [comment]
`webextension-store-meta@1.2.2` published.

I see a more reliable way to extract the version from `AF_initDataCallback`. Will take a closer look when have time.

**Comment by crimx** [comment]
added in `webextension-store-meta@1.2.3`.
