### ISSUE TITLE
Feature request: Extension size and last updated

### ISSUE THREAD

**Issue by aiden2480** [awesome-webextension/webextension-store-meta#8]
Can these fields be extracted from the page, similar to the version? The elements themselves don't have a unique class, but their parents do - `uBIrad` & `ZSMSLb`

```html
<li class="ZbWJPd uBIrad">
    <div class="nws2nb">Updated</div>
    <div>October 13, 2024</div>
</li>
<li class="ZbWJPd ZSMSLb">
    <div class="nws2nb">Size</div>
    <div>3.37MiB</div>
</li>
```

**Comment by crimx** [comment]
`webextension-store-meta@1.2.4` added `size` and `lastUpdated` for both stores.
